#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
UPSTREAM_INPUT="${1:-$ROOT/../upstream}"
UPSTREAM="$(cd "$UPSTREAM_INPUT" && pwd)"
WORKSPACE="$(cd "$ROOT/.." && pwd)"

"$ROOT/insave-build/v0180/reconstruct_v0180_heavy.sh" "$UPSTREAM"

cd "$WORKSPACE"
python3 -m py_compile \
  "$ROOT/insave-build/v0180/apply_v0180_privacy.py" \
  "$ROOT/insave-build/v0181/apply_v0181_social.py"
python3 "$ROOT/insave-build/v0180/apply_v0180_privacy.py"
python3 "$ROOT/insave-build/v0181/apply_v0181_social.py"

HUB="$UPSTREAM/app/src/main/java/com/deniscerri/ytdl/insave/InSaveHubActivity.kt"
COOKIE_VM="$UPSTREAM/app/src/main/java/com/deniscerri/ytdl/database/viewmodel/CookieViewModel.kt"
COOKIE_WEB="$UPSTREAM/app/src/main/java/com/deniscerri/ytdl/ui/more/cookies/WebViewActivity.kt"
MANIFEST="$UPSTREAM/app/src/main/AndroidManifest.xml"
BUILD="$UPSTREAM/app/build.gradle"

# Privacy/security follow-up must be physically present in the final reconstructed source.
! grep -q 'Log.e("Aaa", clip.toString())' "$COOKIE_VM"
grep -q '# Generated by InSave' "$COOKIE_VM"
grep -q 'InSave_Cookies.txt' "$COOKIE_VM"
grep -q 'allowFileAccess = false' "$COOKIE_WEB"
grep -q 'allowContentAccess = false' "$COOKIE_WEB"
grep -q 'MIXED_CONTENT_NEVER_ALLOW' "$COOKIE_WEB"
grep -q 'javaScriptCanOpenWindowsAutomatically = false' "$COOKIE_WEB"
! grep -q 'finishAndRemoveTask()' "$COOKIE_WEB"
grep -A8 'android:name=".ui.more.cookies.WebViewActivity"' "$MANIFEST" | grep -q 'android:exported="false"'
grep -A8 'android:name=".ui.more.settings.advanced.generateyoutubepotokens.webview.PoTokenWebViewLoginActivity"' "$MANIFEST" | grep -q 'android:exported="false"'
grep -A8 'android:name=".receiver.ResumeActivity"' "$MANIFEST" | grep -q 'android:exported="false"'

# Dedicated social UX contracts.
grep -q 'Instagram · Pegar y descargar' "$HUB"
grep -q 'Facebook · Pegar y descargar' "$HUB"
grep -q 'openSocialDownload(InSaveSocialPolicy.Platform.INSTAGRAM)' "$HUB"
grep -q 'openSocialDownload(InSaveSocialPolicy.Platform.FACEBOOK)' "$HUB"
grep -q 'clipboard.primaryClip' "$HUB"
grep -q 'InSaveSocialPolicy.classify' "$HUB"
test -s "$UPSTREAM/app/src/main/java/com/deniscerri/ytdl/insave/InSaveSocialPolicy.kt"
test -s "$UPSTREAM/app/src/test/java/com/deniscerri/ytdl/insave/InSaveSocialPolicyTest.kt"
grep -q 'versionCode 18100' "$BUILD"
grep -q 'versionName "0.18.1-Social-UX-QA"' "$BUILD"

# Preserve v0.17.2/v0.18 critical behavior while adding social shortcuts.
grep -q 'Buscar estados' "$HUB"
grep -q 'Mostrando · ${filtered.size}' "$HUB"
grep -q 'onBackPressedDispatcher.addCallback(this)' "$HUB"
grep -q 'insave_loudness_boost' "$HUB"
grep -q 'applicationId "com.adelvis.insave.recovery"' "$BUILD"

echo 'InSave v0.18.1 social/privacy hardened reconstruction: PASS'
