package com.adelvis.insave.attestationtest;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import android.webkit.CookieManager;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.TextView;

import java.io.File;
import java.io.FileWriter;
import java.util.LinkedHashMap;
import java.util.Map;

public final class MainActivity extends Activity {
    private static final String TAG = "InSaveAttestationQA";
    private static final String WATCH = "https://www.youtube.com/watch?v=aqz-KE-bpKQ";
    private TextView text;
    private WebView webView;
    private boolean exported;

    @Override public void onCreate(Bundle state) {
        super.onCreate(state);
        text = new TextView(this);
        text.setText("Preparando sesión web anónima de YouTube…");
        text.setTextSize(18f);
        text.setPadding(32, 64, 32, 32);
        setContentView(text);

        CookieManager cm = CookieManager.getInstance();
        cm.setAcceptCookie(true);
        cm.removeAllCookies(value -> {
            cm.flush();
            startWebView();
        });
    }

    private void startWebView() {
        webView = new WebView(this);
        WebSettings s = webView.getSettings();
        s.setJavaScriptEnabled(true);
        s.setDomStorageEnabled(true);
        s.setDatabaseEnabled(true);
        s.setLoadsImagesAutomatically(false);
        s.setMediaPlaybackRequiresUserGesture(true);
        CookieManager.getInstance().setAcceptThirdPartyCookies(webView, true);
        webView.setWebViewClient(new WebViewClient() {
            @Override public void onPageFinished(WebView view, String url) {
                Log.i(TAG, "PAGE_FINISHED " + url);
                if (!exported) view.postDelayed(() -> exportCookies(view), 12000L);
            }
        });
        addContentView(webView, new android.view.ViewGroup.LayoutParams(1, 1));
        webView.loadUrl(WATCH);
    }

    private void exportCookies(WebView view) {
        if (exported) return;
        exported = true;
        try {
            CookieManager cm = CookieManager.getInstance();
            cm.flush();
            Map<String, String> cookies = new LinkedHashMap<>();
            collect(cookies, cm.getCookie("https://www.youtube.com/"));
            collect(cookies, cm.getCookie("https://m.youtube.com/"));
            collect(cookies, cm.getCookie(WATCH));

            String ua = view.getSettings().getUserAgentString();
            File out = new File(getExternalFilesDir(null), "youtube-anon-cookies.txt");
            try (FileWriter fw = new FileWriter(out, false)) {
                fw.write("# Netscape HTTP Cookie File\n");
                fw.write("# Generated by InSave WebView QA\n");
                long expiry = System.currentTimeMillis() / 1000L + 86400L * 30L;
                for (Map.Entry<String, String> e : cookies.entrySet()) {
                    fw.write(".youtube.com\tTRUE\t/\tTRUE\t" + expiry + "\t" + e.getKey() + "\t" + e.getValue() + "\n");
                }
            }
            Log.i(TAG, "COOKIE_NAMES " + cookies.keySet());
            Log.i(TAG, "USER_AGENT " + ua);
            Log.i(TAG, "COOKIE_FILE " + out.getAbsolutePath());
            if (cookies.isEmpty()) throw new IllegalStateException("WebView no generó cookies");
            Log.i(TAG, "INSAVE_COOKIE_PRIME_PASS count=" + cookies.size());
            text.setText("PASS: WebView generó " + cookies.size() + " cookies anónimas");
        } catch (Throwable t) {
            Log.e(TAG, "INSAVE_COOKIE_PRIME_FAIL " + t.getClass().getName() + ": " + t.getMessage(), t);
            text.setText("FAIL: " + t.getClass().getSimpleName() + ": " + t.getMessage());
        }
    }

    private static void collect(Map<String, String> target, String header) {
        if (header == null || header.trim().isEmpty()) return;
        for (String part : header.split(";")) {
            String p = part.trim();
            int eq = p.indexOf('=');
            if (eq <= 0) continue;
            target.put(p.substring(0, eq), p.substring(eq + 1));
        }
    }

    @Override protected void onDestroy() {
        if (webView != null) webView.destroy();
        super.onDestroy();
    }
}
