from pathlib import Path
import re

upstream = (Path.cwd() / "upstream").resolve()
src = upstream / "app/src/main/java/com/deniscerri/ytdl"
manifest_path = upstream / "app/src/main/AndroidManifest.xml"


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old in text:
        return text.replace(old, new, 1)
    if new in text:
        return text
    raise SystemExit(f"privacy hardening anchor missing: {label}")

# Cookie import previously printed the entire clipboard cookie file into logcat.
cookie_vm_path = src / "database/viewmodel/CookieViewModel.kt"
cookie_vm = cookie_vm_path.read_text()
cookie_vm = cookie_vm.replace('            Log.e("Aaa", clip.toString())\n', '')
cookie_vm = cookie_vm.replace('# Generated by YTDLnis', '# Generated by InSave')
cookie_vm = cookie_vm.replace('YTDLnis_Cookies.txt', 'InSave_Cookies.txt')
cookie_vm_path.write_text(cookie_vm)

# Generic cookie-login WebView is an internal screen. Treat its URL extra as untrusted,
# remove unsafe WebView capabilities and do not remove the entire application task on Back.
web_path = src / "ui/more/cookies/WebViewActivity.kt"
web = web_path.read_text()
if "import com.deniscerri.ytdl.insave.InSaveInputPolicy" not in web:
    web = web.replace(
        "import com.deniscerri.ytdl.database.viewmodel.CookieViewModel\n",
        "import com.deniscerri.ytdl.database.viewmodel.CookieViewModel\nimport com.deniscerri.ytdl.insave.InSaveInputPolicy\n",
        1,
    )
web = replace_once(
    web,
    '        url = intent.getStringExtra("url") ?: return finish()\n',
    '        url = InSaveInputPolicy.normalizeHttpUrl(intent.getStringExtra("url")) ?: return finish()\n',
    "cookie WebView URL validation",
)
web = web.replace('                finishAndRemoveTask()\n', '                finish()\n')
web = web.replace('                    javaScriptCanOpenWindowsAutomatically = true\n', '                    javaScriptCanOpenWindowsAutomatically = false\n')
settings_anchor = '                    javaScriptCanOpenWindowsAutomatically = false\n'
if '                    allowFileAccess = false\n' not in web:
    web = replace_once(
        web,
        settings_anchor,
        settings_anchor
        + '                    allowFileAccess = false\n'
        + '                    allowContentAccess = false\n'
        + '                    mixedContentMode = WebSettings.MIXED_CONTENT_NEVER_ALLOW\n'
        + '                    setGeolocationEnabled(false)\n',
        "cookie WebView hardened settings",
    )
# Never re-enable geolocation in normal mode.
web = web.replace('                        setGeolocationEnabled(true)\n', '')
old_override = '''                    override fun shouldOverrideUrlLoading(\n                        view: WebView?,\n                        request: WebResourceRequest?\n                    ): Boolean {\n                        if (request?.url?.scheme?.contains("http") == false) {\n                            return true\n                        }\n                        return super.shouldOverrideUrlLoading(view, request)\n                    }\n'''
new_override = '''                    override fun shouldOverrideUrlLoading(\n                        view: WebView?,\n                        request: WebResourceRequest?\n                    ): Boolean {\n                        val safe = InSaveInputPolicy.normalizeHttpUrl(request?.url?.toString()) ?: return true\n                        view?.loadUrl(safe)\n                        return true\n                    }\n'''
web = replace_once(web, old_override, new_override, "cookie WebView navigation validation")
web_path.write_text(web)

# Reduce exported attack surface. System BOOT receiver and explicit share/launcher aliases
# stay exported where Android requires external entry, but internal utility Activities do not.
manifest = manifest_path.read_text()

def set_exported(xml: str, name: str, value: bool) -> str:
    pattern = re.compile(r'(<activity\b[^>]*android:name="' + re.escape(name) + r'"[^>]*)(>)', re.DOTALL)
    m = pattern.search(xml)
    if not m:
        raise SystemExit(f"manifest activity missing: {name}")
    tag = m.group(1)
    replacement = f'android:exported="{str(value).lower()}"'
    if re.search(r'android:exported="(?:true|false)"', tag):
        tag = re.sub(r'android:exported="(?:true|false)"', replacement, tag, count=1)
    else:
        tag += '\n            ' + replacement
    return xml[:m.start()] + tag + m.group(2) + xml[m.end():]

for name in (
    ".ui.more.cookies.WebViewActivity",
    ".ui.more.settings.advanced.generateyoutubepotokens.webview.PoTokenWebViewLoginActivity",
    ".receiver.ResumeActivity",
):
    manifest = set_exported(manifest, name, False)
manifest_path.write_text(manifest)

checks = {
    "clipboard cookie not logged": 'Log.e("Aaa", clip.toString())' not in cookie_vm,
    "cookie WebView validates initial URL": 'InSaveInputPolicy.normalizeHttpUrl(intent.getStringExtra("url"))' in web,
    "cookie WebView blocks file access": 'allowFileAccess = false' in web and 'allowContentAccess = false' in web,
    "cookie WebView blocks mixed content": 'MIXED_CONTENT_NEVER_ALLOW' in web,
    "cookie WebView blocks JS popups": 'javaScriptCanOpenWindowsAutomatically = false' in web,
    "cookie WebView validates navigation": 'normalizeHttpUrl(request?.url?.toString())' in web,
    "no task-destructive back": 'finishAndRemoveTask()' not in web,
}
failed = [name for name, ok in checks.items() if not ok]
if failed:
    raise SystemExit("InSave privacy hardening failed: " + ", ".join(failed))
print("InSave v0.18 cookie/WebView privacy hardening: PASS")
